//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace ComputerExam.Util.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReJobDataHandlerSoap", Namespace="http://tempuri.org/")]
    public partial class ReJobDataHandler : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MySoapHeader mySoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback StudentLoginValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback TeacherLoginValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExamSubjectDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyJobDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyJobScoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyJobDetailScoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMyStudyFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMyJobScoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecPractiseInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLoginOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTopicDBScoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartTrainingOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndTrainingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopicDBListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReJobDataHandler() {
            this.Url = global::ComputerExam.Util.Properties.Settings.Default.ComputerExam_Util_WebReference_ReJobDataHandler;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MySoapHeader MySoapHeaderValue {
            get {
                return this.mySoapHeaderValueField;
            }
            set {
                this.mySoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StudentLoginValidateCompletedEventHandler StudentLoginValidateCompleted;
        
        /// <remarks/>
        public event TeacherLoginValidateCompletedEventHandler TeacherLoginValidateCompleted;
        
        /// <remarks/>
        public event GetExamSubjectDataCompletedEventHandler GetExamSubjectDataCompleted;
        
        /// <remarks/>
        public event GetMyJobDataCompletedEventHandler GetMyJobDataCompleted;
        
        /// <remarks/>
        public event GetMyJobScoreCompletedEventHandler GetMyJobScoreCompleted;
        
        /// <remarks/>
        public event GetMyJobDetailScoreCompletedEventHandler GetMyJobDetailScoreCompleted;
        
        /// <remarks/>
        public event GetMyStudyFileCompletedEventHandler GetMyStudyFileCompleted;
        
        /// <remarks/>
        public event UpdateMyJobScoreCompletedEventHandler UpdateMyJobScoreCompleted;
        
        /// <remarks/>
        public event RecPractiseInfoCompletedEventHandler RecPractiseInfoCompleted;
        
        /// <remarks/>
        public event UpdateLoginOutCompletedEventHandler UpdateLoginOutCompleted;
        
        /// <remarks/>
        public event UpdateTopicDBScoreCompletedEventHandler UpdateTopicDBScoreCompleted;
        
        /// <remarks/>
        public event StartTrainingCompletedEventHandler StartTrainingCompleted;
        
        /// <remarks/>
        public event EndTrainingCompletedEventHandler EndTrainingCompleted;
        
        /// <remarks/>
        public event GetTopicDBListCompletedEventHandler GetTopicDBListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StudentLoginValidate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StudentLoginValidate(string InStudentCode, string InPassword, ref string ExamineeName) {
            object[] results = this.Invoke("StudentLoginValidate", new object[] {
                        InStudentCode,
                        InPassword,
                        ExamineeName});
            ExamineeName = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StudentLoginValidateAsync(string InStudentCode, string InPassword, string ExamineeName) {
            this.StudentLoginValidateAsync(InStudentCode, InPassword, ExamineeName, null);
        }
        
        /// <remarks/>
        public void StudentLoginValidateAsync(string InStudentCode, string InPassword, string ExamineeName, object userState) {
            if ((this.StudentLoginValidateOperationCompleted == null)) {
                this.StudentLoginValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStudentLoginValidateOperationCompleted);
            }
            this.InvokeAsync("StudentLoginValidate", new object[] {
                        InStudentCode,
                        InPassword,
                        ExamineeName}, this.StudentLoginValidateOperationCompleted, userState);
        }
        
        private void OnStudentLoginValidateOperationCompleted(object arg) {
            if ((this.StudentLoginValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StudentLoginValidateCompleted(this, new StudentLoginValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TeacherLoginValidate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TeacherLoginValidate(string LoginUserName, string InPassword) {
            object[] results = this.Invoke("TeacherLoginValidate", new object[] {
                        LoginUserName,
                        InPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TeacherLoginValidateAsync(string LoginUserName, string InPassword) {
            this.TeacherLoginValidateAsync(LoginUserName, InPassword, null);
        }
        
        /// <remarks/>
        public void TeacherLoginValidateAsync(string LoginUserName, string InPassword, object userState) {
            if ((this.TeacherLoginValidateOperationCompleted == null)) {
                this.TeacherLoginValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTeacherLoginValidateOperationCompleted);
            }
            this.InvokeAsync("TeacherLoginValidate", new object[] {
                        LoginUserName,
                        InPassword}, this.TeacherLoginValidateOperationCompleted, userState);
        }
        
        private void OnTeacherLoginValidateOperationCompleted(object arg) {
            if ((this.TeacherLoginValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TeacherLoginValidateCompleted(this, new TeacherLoginValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExamSubjectData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetExamSubjectData(string InStudentCode) {
            object[] results = this.Invoke("GetExamSubjectData", new object[] {
                        InStudentCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetExamSubjectDataAsync(string InStudentCode) {
            this.GetExamSubjectDataAsync(InStudentCode, null);
        }
        
        /// <remarks/>
        public void GetExamSubjectDataAsync(string InStudentCode, object userState) {
            if ((this.GetExamSubjectDataOperationCompleted == null)) {
                this.GetExamSubjectDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExamSubjectDataOperationCompleted);
            }
            this.InvokeAsync("GetExamSubjectData", new object[] {
                        InStudentCode}, this.GetExamSubjectDataOperationCompleted, userState);
        }
        
        private void OnGetExamSubjectDataOperationCompleted(object arg) {
            if ((this.GetExamSubjectDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExamSubjectDataCompleted(this, new GetExamSubjectDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyJobData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMyJobData(string InStudentCode, string InStartTime, string InEndTime, int InDataType) {
            object[] results = this.Invoke("GetMyJobData", new object[] {
                        InStudentCode,
                        InStartTime,
                        InEndTime,
                        InDataType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMyJobDataAsync(string InStudentCode, string InStartTime, string InEndTime, int InDataType) {
            this.GetMyJobDataAsync(InStudentCode, InStartTime, InEndTime, InDataType, null);
        }
        
        /// <remarks/>
        public void GetMyJobDataAsync(string InStudentCode, string InStartTime, string InEndTime, int InDataType, object userState) {
            if ((this.GetMyJobDataOperationCompleted == null)) {
                this.GetMyJobDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyJobDataOperationCompleted);
            }
            this.InvokeAsync("GetMyJobData", new object[] {
                        InStudentCode,
                        InStartTime,
                        InEndTime,
                        InDataType}, this.GetMyJobDataOperationCompleted, userState);
        }
        
        private void OnGetMyJobDataOperationCompleted(object arg) {
            if ((this.GetMyJobDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyJobDataCompleted(this, new GetMyJobDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyJobScore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMyJobScore(string InStudentCode, string InStartTime, string InEndTime, int InDataType) {
            object[] results = this.Invoke("GetMyJobScore", new object[] {
                        InStudentCode,
                        InStartTime,
                        InEndTime,
                        InDataType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMyJobScoreAsync(string InStudentCode, string InStartTime, string InEndTime, int InDataType) {
            this.GetMyJobScoreAsync(InStudentCode, InStartTime, InEndTime, InDataType, null);
        }
        
        /// <remarks/>
        public void GetMyJobScoreAsync(string InStudentCode, string InStartTime, string InEndTime, int InDataType, object userState) {
            if ((this.GetMyJobScoreOperationCompleted == null)) {
                this.GetMyJobScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyJobScoreOperationCompleted);
            }
            this.InvokeAsync("GetMyJobScore", new object[] {
                        InStudentCode,
                        InStartTime,
                        InEndTime,
                        InDataType}, this.GetMyJobScoreOperationCompleted, userState);
        }
        
        private void OnGetMyJobScoreOperationCompleted(object arg) {
            if ((this.GetMyJobScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyJobScoreCompleted(this, new GetMyJobScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyJobDetailScore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMyJobDetailScore(string InStudentCode, string InHWID, int InDataType) {
            object[] results = this.Invoke("GetMyJobDetailScore", new object[] {
                        InStudentCode,
                        InHWID,
                        InDataType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMyJobDetailScoreAsync(string InStudentCode, string InHWID, int InDataType) {
            this.GetMyJobDetailScoreAsync(InStudentCode, InHWID, InDataType, null);
        }
        
        /// <remarks/>
        public void GetMyJobDetailScoreAsync(string InStudentCode, string InHWID, int InDataType, object userState) {
            if ((this.GetMyJobDetailScoreOperationCompleted == null)) {
                this.GetMyJobDetailScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyJobDetailScoreOperationCompleted);
            }
            this.InvokeAsync("GetMyJobDetailScore", new object[] {
                        InStudentCode,
                        InHWID,
                        InDataType}, this.GetMyJobDetailScoreOperationCompleted, userState);
        }
        
        private void OnGetMyJobDetailScoreOperationCompleted(object arg) {
            if ((this.GetMyJobDetailScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyJobDetailScoreCompleted(this, new GetMyJobDetailScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMyStudyFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMyStudyFile(string InStudentCode, string InStartTime, string InEndTime) {
            object[] results = this.Invoke("GetMyStudyFile", new object[] {
                        InStudentCode,
                        InStartTime,
                        InEndTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMyStudyFileAsync(string InStudentCode, string InStartTime, string InEndTime) {
            this.GetMyStudyFileAsync(InStudentCode, InStartTime, InEndTime, null);
        }
        
        /// <remarks/>
        public void GetMyStudyFileAsync(string InStudentCode, string InStartTime, string InEndTime, object userState) {
            if ((this.GetMyStudyFileOperationCompleted == null)) {
                this.GetMyStudyFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMyStudyFileOperationCompleted);
            }
            this.InvokeAsync("GetMyStudyFile", new object[] {
                        InStudentCode,
                        InStartTime,
                        InEndTime}, this.GetMyStudyFileOperationCompleted, userState);
        }
        
        private void OnGetMyStudyFileOperationCompleted(object arg) {
            if ((this.GetMyStudyFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMyStudyFileCompleted(this, new GetMyStudyFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMyJobScore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMyJobScore(string InStudentCode, string InHWID, string InXmlScore, ref string Msg) {
            object[] results = this.Invoke("UpdateMyJobScore", new object[] {
                        InStudentCode,
                        InHWID,
                        InXmlScore,
                        Msg});
            Msg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMyJobScoreAsync(string InStudentCode, string InHWID, string InXmlScore, string Msg) {
            this.UpdateMyJobScoreAsync(InStudentCode, InHWID, InXmlScore, Msg, null);
        }
        
        /// <remarks/>
        public void UpdateMyJobScoreAsync(string InStudentCode, string InHWID, string InXmlScore, string Msg, object userState) {
            if ((this.UpdateMyJobScoreOperationCompleted == null)) {
                this.UpdateMyJobScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMyJobScoreOperationCompleted);
            }
            this.InvokeAsync("UpdateMyJobScore", new object[] {
                        InStudentCode,
                        InHWID,
                        InXmlScore,
                        Msg}, this.UpdateMyJobScoreOperationCompleted, userState);
        }
        
        private void OnUpdateMyJobScoreOperationCompleted(object arg) {
            if ((this.UpdateMyJobScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMyJobScoreCompleted(this, new UpdateMyJobScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecPractiseInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RecPractiseInfo(int InRecType, string InStudentCode, string InHWID) {
            object[] results = this.Invoke("RecPractiseInfo", new object[] {
                        InRecType,
                        InStudentCode,
                        InHWID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecPractiseInfoAsync(int InRecType, string InStudentCode, string InHWID) {
            this.RecPractiseInfoAsync(InRecType, InStudentCode, InHWID, null);
        }
        
        /// <remarks/>
        public void RecPractiseInfoAsync(int InRecType, string InStudentCode, string InHWID, object userState) {
            if ((this.RecPractiseInfoOperationCompleted == null)) {
                this.RecPractiseInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecPractiseInfoOperationCompleted);
            }
            this.InvokeAsync("RecPractiseInfo", new object[] {
                        InRecType,
                        InStudentCode,
                        InHWID}, this.RecPractiseInfoOperationCompleted, userState);
        }
        
        private void OnRecPractiseInfoOperationCompleted(object arg) {
            if ((this.RecPractiseInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecPractiseInfoCompleted(this, new RecPractiseInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLoginOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateLoginOut(string InStudentCode) {
            object[] results = this.Invoke("UpdateLoginOut", new object[] {
                        InStudentCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateLoginOutAsync(string InStudentCode) {
            this.UpdateLoginOutAsync(InStudentCode, null);
        }
        
        /// <remarks/>
        public void UpdateLoginOutAsync(string InStudentCode, object userState) {
            if ((this.UpdateLoginOutOperationCompleted == null)) {
                this.UpdateLoginOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLoginOutOperationCompleted);
            }
            this.InvokeAsync("UpdateLoginOut", new object[] {
                        InStudentCode}, this.UpdateLoginOutOperationCompleted, userState);
        }
        
        private void OnUpdateLoginOutOperationCompleted(object arg) {
            if ((this.UpdateLoginOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLoginOutCompleted(this, new UpdateLoginOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTopicDBScore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateTopicDBScore(string InStudentCode, string InXmlScore, ref string Msg) {
            object[] results = this.Invoke("UpdateTopicDBScore", new object[] {
                        InStudentCode,
                        InXmlScore,
                        Msg});
            Msg = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTopicDBScoreAsync(string InStudentCode, string InXmlScore, string Msg) {
            this.UpdateTopicDBScoreAsync(InStudentCode, InXmlScore, Msg, null);
        }
        
        /// <remarks/>
        public void UpdateTopicDBScoreAsync(string InStudentCode, string InXmlScore, string Msg, object userState) {
            if ((this.UpdateTopicDBScoreOperationCompleted == null)) {
                this.UpdateTopicDBScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTopicDBScoreOperationCompleted);
            }
            this.InvokeAsync("UpdateTopicDBScore", new object[] {
                        InStudentCode,
                        InXmlScore,
                        Msg}, this.UpdateTopicDBScoreOperationCompleted, userState);
        }
        
        private void OnUpdateTopicDBScoreOperationCompleted(object arg) {
            if ((this.UpdateTopicDBScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTopicDBScoreCompleted(this, new UpdateTopicDBScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartTraining", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartTraining(ref string Msg) {
            object[] results = this.Invoke("StartTraining", new object[] {
                        Msg});
            Msg = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StartTrainingAsync(string Msg) {
            this.StartTrainingAsync(Msg, null);
        }
        
        /// <remarks/>
        public void StartTrainingAsync(string Msg, object userState) {
            if ((this.StartTrainingOperationCompleted == null)) {
                this.StartTrainingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartTrainingOperationCompleted);
            }
            this.InvokeAsync("StartTraining", new object[] {
                        Msg}, this.StartTrainingOperationCompleted, userState);
        }
        
        private void OnStartTrainingOperationCompleted(object arg) {
            if ((this.StartTrainingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartTrainingCompleted(this, new StartTrainingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndTraining", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EndTraining(ref string Msg) {
            object[] results = this.Invoke("EndTraining", new object[] {
                        Msg});
            Msg = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EndTrainingAsync(string Msg) {
            this.EndTrainingAsync(Msg, null);
        }
        
        /// <remarks/>
        public void EndTrainingAsync(string Msg, object userState) {
            if ((this.EndTrainingOperationCompleted == null)) {
                this.EndTrainingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndTrainingOperationCompleted);
            }
            this.InvokeAsync("EndTraining", new object[] {
                        Msg}, this.EndTrainingOperationCompleted, userState);
        }
        
        private void OnEndTrainingOperationCompleted(object arg) {
            if ((this.EndTrainingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndTrainingCompleted(this, new EndTrainingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTopicDBList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTopicDBList(string TopicDBName, string TopicDBCode, string InStartTime, string InEndTime) {
            object[] results = this.Invoke("GetTopicDBList", new object[] {
                        TopicDBName,
                        TopicDBCode,
                        InStartTime,
                        InEndTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopicDBListAsync(string TopicDBName, string TopicDBCode, string InStartTime, string InEndTime) {
            this.GetTopicDBListAsync(TopicDBName, TopicDBCode, InStartTime, InEndTime, null);
        }
        
        /// <remarks/>
        public void GetTopicDBListAsync(string TopicDBName, string TopicDBCode, string InStartTime, string InEndTime, object userState) {
            if ((this.GetTopicDBListOperationCompleted == null)) {
                this.GetTopicDBListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopicDBListOperationCompleted);
            }
            this.InvokeAsync("GetTopicDBList", new object[] {
                        TopicDBName,
                        TopicDBCode,
                        InStartTime,
                        InEndTime}, this.GetTopicDBListOperationCompleted, userState);
        }
        
        private void OnGetTopicDBListOperationCompleted(object arg) {
            if ((this.GetTopicDBListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopicDBListCompleted(this, new GetTopicDBListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class MySoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string authCodeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StudentLoginValidateCompletedEventHandler(object sender, StudentLoginValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StudentLoginValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StudentLoginValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ExamineeName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void TeacherLoginValidateCompletedEventHandler(object sender, TeacherLoginValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TeacherLoginValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TeacherLoginValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetExamSubjectDataCompletedEventHandler(object sender, GetExamSubjectDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExamSubjectDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExamSubjectDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMyJobDataCompletedEventHandler(object sender, GetMyJobDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyJobDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyJobDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMyJobScoreCompletedEventHandler(object sender, GetMyJobScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyJobScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyJobScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMyJobDetailScoreCompletedEventHandler(object sender, GetMyJobDetailScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyJobDetailScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyJobDetailScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetMyStudyFileCompletedEventHandler(object sender, GetMyStudyFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMyStudyFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMyStudyFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateMyJobScoreCompletedEventHandler(object sender, UpdateMyJobScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMyJobScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMyJobScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void RecPractiseInfoCompletedEventHandler(object sender, RecPractiseInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecPractiseInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecPractiseInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateLoginOutCompletedEventHandler(object sender, UpdateLoginOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateLoginOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateLoginOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void UpdateTopicDBScoreCompletedEventHandler(object sender, UpdateTopicDBScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTopicDBScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTopicDBScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartTrainingCompletedEventHandler(object sender, StartTrainingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartTrainingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartTrainingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EndTrainingCompletedEventHandler(object sender, EndTrainingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndTrainingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndTrainingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Msg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetTopicDBListCompletedEventHandler(object sender, GetTopicDBListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopicDBListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopicDBListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591